"""Econometric extension points for the credit risk lab.

This package contains the first implemented layer of the repo's econometrics
extensions: calibration, panel diagnostics, duration tables, forward hazard
paths, macro scenario paths, Markov migration, continuous-time intensity
diagnostics, measurement-error sensitivity, causal audits, heterogeneity
checks, and model-selection helpers.
"""

from .calibration import brier_score, calibration_table, intercept_shift_recalibration, isotonic_recalibration, segment_calibration_drift
from .causal import omitted_variable_sensitivity, policy_shock_sensitivity, variable_identification_audit
from .continuous_time import (
    build_compensated_process_from_intervals,
    build_default_counting_process,
    estimate_ctmc_generator_from_durations,
    estimate_default_intensity_from_intervals,
    estimate_piecewise_default_intensity,
    survival_probability_from_intensity,
)
from .continuous_state import (
    ContinuousCreditStateGrid,
    beurling_deny_credit_decomposition,
    build_continuous_credit_state_grid,
    cheeger_energy_credit_proxy,
    default_boundary_capacity_proxy,
    default_probability_from_generator,
    ou_credit_quality_generator,
    polar_state_diagnostic,
    regularity_diagnostics_for_grid,
)
from .duration import baseline_hazard_by_segment, competing_risk_cumulative_incidence, cure_relapse_table, duration_hazard_table, fit_competing_risk_logits
from .forward_hazard import build_forward_panel, cumulative_pd_from_hazard_path, score_forward_pd_paths
from .heterogeneity import coefficient_stability_table, empirical_bayes_segment_shrinkage, fit_segment_binary_logits, segment_performance_table
from .limited_dep import fit_binary_logit, predict_binary_logit, prepare_regression_design
from .macro import MacroAR1Model, MacroVARModel, build_macro_scenario_paths, fit_ar1_macro_model, fit_var_macro_model, forecast_macro_path, forecast_var_macro_path
from .markov import (
    ABSORBING_STATES,
    CREDIT_STATES,
    CovariateTransitionModel,
    GeneratorEmbeddingDiagnostics,
    MarkovTransitionModel,
    aggregate_transition_matrix,
    absorption_summary,
    assign_macro_regime,
    build_transition_panel,
    build_markov_scenario_matrices,
    compare_markov_to_survival_pd,
    covariate_markov_default_pd,
    dirichlet_transition_energy,
    fit_covariate_transition_model,
    fit_macro_regime_transition_matrices,
    fit_markov_transition_model,
    markov_implied_default_pd,
    matrix_log_generator,
    n_step_transition_matrix,
    predict_covariate_transition_probabilities,
    project_generator_to_valid_rates,
    regularize_state_scores,
    reversibility_diagnostics,
    score_smoothness_diagnostics,
    stage_transition_matrix,
    transition_generator,
    transition_matrices_by_group,
)
from .measurement_error import inject_numeric_measurement_error, missingness_by_segment, prediction_noise_sensitivity
from .model_selection import CandidateSpec, compare_binary_model_specs, select_best_model
from .panel import add_interaction_terms, add_polynomial_terms, add_vintage_and_age_columns, cohort_performance_table, poolability_diagnostic, within_transform

__all__ = [
    "ABSORBING_STATES",
    "CREDIT_STATES",
    "CandidateSpec",
    "ContinuousCreditStateGrid",
    "CovariateTransitionModel",
    "GeneratorEmbeddingDiagnostics",
    "MacroAR1Model",
    "MacroVARModel",
    "MarkovTransitionModel",
    "aggregate_transition_matrix",
    "absorption_summary",
    "add_interaction_terms",
    "add_polynomial_terms",
    "add_vintage_and_age_columns",
    "assign_macro_regime",
    "baseline_hazard_by_segment",
    "beurling_deny_credit_decomposition",
    "brier_score",
    "build_compensated_process_from_intervals",
    "build_continuous_credit_state_grid",
    "build_default_counting_process",
    "build_forward_panel",
    "build_markov_scenario_matrices",
    "build_macro_scenario_paths",
    "build_transition_panel",
    "calibration_table",
    "cheeger_energy_credit_proxy",
    "coefficient_stability_table",
    "cohort_performance_table",
    "compare_markov_to_survival_pd",
    "compare_binary_model_specs",
    "competing_risk_cumulative_incidence",
    "covariate_markov_default_pd",
    "cure_relapse_table",
    "cumulative_pd_from_hazard_path",
    "default_boundary_capacity_proxy",
    "default_probability_from_generator",
    "dirichlet_transition_energy",
    "duration_hazard_table",
    "empirical_bayes_segment_shrinkage",
    "estimate_ctmc_generator_from_durations",
    "estimate_default_intensity_from_intervals",
    "estimate_piecewise_default_intensity",
    "fit_ar1_macro_model",
    "fit_binary_logit",
    "fit_competing_risk_logits",
    "fit_covariate_transition_model",
    "fit_macro_regime_transition_matrices",
    "fit_markov_transition_model",
    "fit_segment_binary_logits",
    "fit_var_macro_model",
    "forecast_macro_path",
    "forecast_var_macro_path",
    "inject_numeric_measurement_error",
    "intercept_shift_recalibration",
    "isotonic_recalibration",
    "markov_implied_default_pd",
    "matrix_log_generator",
    "missingness_by_segment",
    "n_step_transition_matrix",
    "ou_credit_quality_generator",
    "omitted_variable_sensitivity",
    "polar_state_diagnostic",
    "policy_shock_sensitivity",
    "poolability_diagnostic",
    "predict_covariate_transition_probabilities",
    "prediction_noise_sensitivity",
    "predict_binary_logit",
    "prepare_regression_design",
    "project_generator_to_valid_rates",
    "regularity_diagnostics_for_grid",
    "regularize_state_scores",
    "reversibility_diagnostics",
    "score_forward_pd_paths",
    "score_smoothness_diagnostics",
    "segment_performance_table",
    "segment_calibration_drift",
    "select_best_model",
    "stage_transition_matrix",
    "survival_probability_from_intensity",
    "transition_generator",
    "transition_matrices_by_group",
    "variable_identification_audit",
    "within_transform",
]
